//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qw.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Измерительное_оборудование
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Измерительное_оборудование()
        {
            this.Методика = new HashSet<Методика>();
            this.Методика1 = new HashSet<Методика>();
            this.Методика2 = new HashSet<Методика>();
            this.Пикет_ИзмерительноеОборудование = new HashSet<Пикет_ИзмерительноеОборудование>();
        }
    
        public int id { get; set; }
        public string название_оборудования { get; set; }
        public string инв__номер { get; set; }
        public Nullable<System.DateTime> дата_приобретения { get; set; }
        public Nullable<System.DateTime> дата_проверки { get; set; }
        public string характеристики_описание { get; set; }
        public Nullable<System.DateTime> дата_добавления_записи { get; set; }
        public Nullable<System.DateTime> дата_последнего_изменения_записи { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Методика> Методика { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Методика> Методика1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Методика> Методика2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пикет_ИзмерительноеОборудование> Пикет_ИзмерительноеОборудование { get; set; }
    }
}
