//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qw.database
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Проект
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Проект()
        {
            this.Площадь = new HashSet<Площадь>();
        }
    
        public int id { get; set; }
        public string название { get; set; }
        public Nullable<int> id_заказчика { get; set; }
        public Nullable<int> id_договора { get; set; }
        public Nullable<System.DateTime> дата_добавления_записи { get; set; }
        public Nullable<System.DateTime> дата_последнего_изменения_записи { get; set; }
        public Nullable<bool> удален { get; set; }
    
        public virtual Договор Договор { get; set; }
        public virtual Заказчик Заказчик { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Площадь> Площадь { get; set; }

        public int количество_площадей
        {
            get 
            { 
                return this.Площадь.Where(x => x.удален != true).Count(); 
            }
        }
    }
}
